services:
  # Local PostgreSQL database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test -d test']
      interval: 10s
      timeout: 5s
      retries: 10

  # One-off migrations service (runs and exits)
  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test
      NODE_ENV: development
    command: pnpm --filter db run migrate

  # One-off seed service (runs and exits)
  db-seed:
    build:
      context: .
      dockerfile: apps/seed/Dockerfile
      target: production
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test
      RPC_URL: ${RPC_URL}
      MNEMONIC: ${MNEMONIC}
    networks:
      - app-network

  # EVM chain indexer
  indexer-evm:
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile
      target: production
    container_name: indexer-evm
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
      db-seed:
        condition: service_completed_successfully
    environment:
      RPC_URL: ${RPC_URL}
      DATABASE_URL: postgresql://test:test@postgres:5432/test
    volumes:
      - indexer_evm_logs:/app/logs
      - indexer_evm_state:/app/state
    networks:
      - app-network

  # API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: production
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
      db-seed:
        condition: service_completed_successfully
    environment:
      MNEMONIC: ${MNEMONIC}
      RPC_URL: ${RPC_URL}
      DATABASE_URL: postgresql://test:test@postgres:5432/test
    volumes:
      - api_logs:/app/logs
      - api_state:/app/state
    networks:
      - app-network


networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  indexer_evm_logs:
    driver: local
  indexer_evm_state:
    driver: local
  api_logs:
    driver: local
  api_state:
    driver: local
  postgres_data:
    driver: local
